# Generated by Django 2.1.3 on 2021-10-15 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=12)),
                ('profile_pic', models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='photos/')),
                ('hospital_name', models.CharField(blank=True, max_length=70)),
                ('degree_type', models.CharField(choices=[('MBBS', 'Bachelor of Medicine, Bachelor of Surgery(MBBS)'), ('BDS', 'Bachelor of Dental Surgery(BDS)'), ('BAMS', 'Bachelor of Ayurvedic Medicine and Surgery(BAMS)'), ('BUMS', 'Bachelor of Unani Medicine and Surgery(BUMS)'), ('BHMS', 'Bachelor of Homeopathy Medicine and Surgery(BHMS)'), ('BYNS', 'Bachelor of Yoga and Naturopathy Sciences(BYNS)'), ('B.V.Sc & AH', 'Bachelor of Veterinary Sciences and Animal Husbandry(BVSc&AH)'), ('MD', 'Doctor of Medicine(MD)'), ('MS', 'Master of Surgery(MS)'), ('DM', 'Doctorate of Medicine(DM)')], max_length=50)),
                ('specialities_type', models.CharField(choices=[('ENT', 'Ear, Nose and Throat'), ('GS', 'General Surgery'), ('OP', 'Ophthalmology'), ('OR', 'Orthopaedics'), ('OAG', 'Obstetrics and Gynaecology'), ('DVL', 'Dermatology, Venerology and Leprosy'), ('AST', 'Anaesthesiology'), ('PSY', 'Psychiatry'), ('PTH', 'Pathology'), ('SVD', 'Skin and Venereal diseases'), ('PHRM', 'Pharmacology'), ('PMR', 'Physical Medicine and Rehabilitation'), ('PHY', 'Physiology'), ('CRD', 'Cardiology'), ('PDT', 'Paediatrics')], max_length=50)),
                ('dob', models.CharField(max_length=8)),
                ('age', models.PositiveIntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('disease', models.CharField(max_length=200)),
                ('medicine', models.TextField()),
                ('charges', models.PositiveIntegerField()),
                ('hospital_name', models.CharField(blank=True, max_length=70)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=12)),
                ('profile_pic', models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='photos/')),
                ('dob', models.CharField(max_length=8)),
                ('age', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
