# Generated by Django 3.2.8 on 2021-10-15 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ghsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='dob',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('doctor_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_app', to=settings.AUTH_USER_MODEL)),
                ('user_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
