# Generated by Django 3.2.8 on 2021-10-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghsapp', '0004_alter_userinfo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='static/photos/'),
        ),
    ]
