# Generated by Django 3.2.8 on 2021-10-16 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ghsapp', '0005_alter_doctorinfo_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_time', models.CharField(choices=[('M', 'Mal'), ('F', 'Female')], max_length=1)),
                ('recommendation', models.CharField(choices=[('M', 'Mal'), ('F', 'Female')], max_length=1)),
                ('feedback', models.TextField(blank=True)),
                ('doctor_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_feed', to=settings.AUTH_USER_MODEL)),
                ('user_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
